services:
  mysql:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: irrigation_db
    ports:
      - "3306:3306"
    networks:
      - irrigation-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  irrigation-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      mysql:
          condition: service_healthy
    environment:
      - PROFILE=prd
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/irrigation_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - irrigation-network

networks:
  irrigation-network:
    driver: bridge

volumes:
  mysql-data: