
# -----------------| USER |-----------------

CREATE TABLE TBL_USER (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    ACTIVE TINYINT(1) DEFAULT 0 CHECK (ACTIVE BETWEEN 0 AND 1) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(10) NOT NULL,
    PRIMARY KEY (USER_ID)
);

INSERT INTO TBL_USER (USER_ID, ACTIVE, EMAIL, NAME, PASSWORD, ROLE)
VALUES (1, 1, 'admin@admin.com', 'System Administrator', '$2a$10$dxlL.53a1jUX4Zee3E1scuXYLG8Zg.4qydFVlcIzSDsitcd900OKC', 'ADMIN');
-- Password '1234abcd' after encrypt


# -----------------| AREA |-----------------

CREATE TABLE TBL_AREA (
    AREA_ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255),
    LOCATION VARCHAR(255),
    AREA_SIZE VARCHAR(255),
    PRIMARY KEY (AREA_ID)
);

# -----------------| NOTIFICATION |-----------------

CREATE TABLE TBL_NOTIFICATION (
    NOTIFICATION_ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255),
    TIMESTAMP TIMESTAMP,
    SENSOR_ID BIGINT,
    PRIMARY KEY (NOTIFICATION_ID)
);

# -----------------| SENSOR |-----------------

CREATE TABLE TBL_SENSOR (
    SENSOR_ID BIGINT NOT NULL AUTO_INCREMENT,
    LOCATION VARCHAR(255),
    TYPE VARCHAR(255),
    AREA_ID BIGINT,
    PRIMARY KEY (SENSOR_ID)
);

# -----------------| WEATHER |-----------------

CREATE TABLE TBL_WEATHER (
    WEATHER_ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255),
    HUMIDITY INT,
    TEMPERATURE INT,
    TIMESTAMP TIMESTAMP,
    SENSOR_ID BIGINT,
    PRIMARY KEY (WEATHER_ID)
);

# -----------------| SCHEDULE |-----------------

CREATE TABLE TBL_SCHEDULE (
    SCHEDULE_ID BIGINT NOT NULL AUTO_INCREMENT,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    PRIMARY KEY (SCHEDULE_ID)
);

# -----------------| FK CONSTRAINTS |-----------------

ALTER TABLE TBL_NOTIFICATION
    ADD CONSTRAINT FK_NOTIFICATION_SENSOR_ID
        FOREIGN KEY (SENSOR_ID)
            REFERENCES TBL_SENSOR(SENSOR_ID);

ALTER TABLE TBL_SENSOR
    ADD CONSTRAINT FK_SENSOR_AREA_ID
        FOREIGN KEY (AREA_ID)
            REFERENCES TBL_AREA(AREA_ID);

ALTER TABLE TBL_WEATHER
    ADD CONSTRAINT FK_WEATHER_SENSOR_ID
        FOREIGN KEY (SENSOR_ID)
            REFERENCES TBL_SENSOR(SENSOR_ID);
