-----------------| USER |-----------------

CREATE SEQUENCE SEQ_USER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USER(
    ID INTEGER DEFAULT SEQ_USER.NEXTVAL NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    ACTIVE NUMBER(1) NOT NULL
    );

INSERT INTO TBL_USER VALUES (1, "System Administrator", "admin@admin.com", "admin123", "ADMIN", true);

-----------------| AREA |-----------------

CREATE SEQUENCE SEQ_AREA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- TO DO: CREATE TABLE

-----------------| NOTIFICATION |-----------------

CREATE SEQUENCE SEQ_NOTIFICATION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- TO DO: CREATE TABLE

-----------------| SENSOR |-----------------

CREATE SEQUENCE SEQ_SENSOR
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- TO DO: CREATE TABLE

-----------------| WEATHER |-----------------

CREATE SEQUENCE SEQ_WEATHER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- TO DO: CREATE TABLE

-----------------| SCHEDULE |-----------------

-- TO DO: CREATE SEQUENCE

-- TO DO: CREATE TABLE